import { requestUrl } from 'obsidian';
import type { SubtitleEntry, VideoInfo } from '../types';
import { SubtitleParser } from './SubtitleParser';

/**
 * Tier 0：不需要任何外部工具，從 YouTube 抓取字幕
 *
 * 使用 YouTube 的 timedtext XML API（srv1 格式），
 * 回傳乾淨的一句一條字幕，不像 VTT/JSON3 有滾動視窗重複問題。
 */
export class YouTubeTranscript {

    static async fetch(url: string, preferredLang = 'en'): Promise<{
        subtitles: SubtitleEntry[];
        video: VideoInfo;
    }> {
        const videoId = this.extractVideoId(url);
        if (!videoId) {
            throw new Error(`無法從 URL 解析 YouTube 影片 ID：${url}`);
        }

        const pageHtml = await this.fetchPage(videoId);
        const title    = this.extractTitle(pageHtml);
        const tracks   = this.extractCaptionTracks(pageHtml);

        if (tracks.length === 0) {
            throw new Error(
                '此影片沒有可用字幕。\n請嘗試使用 Tier 1（yt-dlp）或 Tier 2（Whisper 轉錄）。'
            );
        }

        const track = this.selectTrack(tracks, preferredLang);
        console.log(`[VLL] 選擇字幕軌道：lang=${track.languageCode}, kind=${track.kind}`);

        // 嘗試 srv1（timedtext XML）格式
        const xmlUrl  = this.buildSrv1Url(track.baseUrl);
        const response = await requestUrl({ url: xmlUrl });
        console.log(`[VLL] srv1 狀態：${response.status}，長度：${response.text.length}`);

        let subtitles = SubtitleParser.parseTimedtextXml(response.text);
        console.log(`[VLL] srv1 解析到 ${subtitles.length} 條字幕`);

        // srv1 對 ASR 字幕有時回傳空內容，改用 JSON3 + aAppend 去重
        if (subtitles.length === 0) {
            console.log('[VLL] srv1 為空，改用 JSON3 格式...');
            const json3Url      = this.buildJson3Url(track.baseUrl);
            const json3Response = await requestUrl({ url: json3Url });
            subtitles = SubtitleParser.parseJSON3Dedup(json3Response.text);
            console.log(`[VLL] JSON3 解析到 ${subtitles.length} 條字幕`);
        }

        if (subtitles.length === 0) {
            throw new Error('Tier 0 無法取得字幕，請嘗試 Tier 1（需要 yt-dlp）');
        }

        const video: VideoInfo = {
            title:  title ?? `YouTube 影片 ${videoId}`,
            source: `https://www.youtube.com/watch?v=${videoId}`,
            type:   'youtube',
        };

        return { subtitles, video };
    }

    /** 取得可用字幕語言清單 */
    static async getAvailableLanguages(url: string): Promise<{
        code: string;
        name: string;
        isAutoGenerated: boolean;
    }[]> {
        const videoId = this.extractVideoId(url);
        if (!videoId) throw new Error('無法解析影片 ID');

        const pageHtml = await this.fetchPage(videoId);
        const tracks   = this.extractCaptionTracks(pageHtml);

        return tracks.map(track => ({
            code:            track.languageCode,
            name:            track.name?.simpleText ?? track.languageCode,
            isAutoGenerated: track.kind === 'asr',
        }));
    }

    /**
     * 從 YouTube URL 提取影片 ID
     * 支援格式：watch?v=、youtu.be/、/embed/、/shorts/
     */
    static extractVideoId(url: string): string | null {
        const patterns = [
            /[?&]v=([^&#]+)/,
            /youtu\.be\/([^?&#]+)/,
            /\/embed\/([^?&#]+)/,
            /\/shorts\/([^?&#]+)/,
        ];
        for (const pattern of patterns) {
            const match = url.match(pattern);
            if (match?.[1]) return match[1];
        }
        return null;
    }

    // ===== 私有方法 =====

    private static async fetchPage(videoId: string): Promise<string> {
        const response = await requestUrl({
            url: `https://www.youtube.com/watch?v=${videoId}`,
            headers: {
                'Accept-Language': 'en-US,en;q=0.9',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            },
        });
        if (response.status !== 200) {
            throw new Error(`YouTube 頁面請求失敗，狀態碼：${response.status}`);
        }
        return response.text;
    }

    private static extractTitle(html: string): string | null {
        const ogMatch    = html.match(/property="og:title"\s+content="([^"]+)"/);
        if (ogMatch?.[1]) return ogMatch[1].trim();
        const titleMatch = html.match(/<title>([^<]+)<\/title>/);
        if (titleMatch?.[1]) return titleMatch[1].replace(' - YouTube', '').trim();
        return null;
    }

    private static extractCaptionTracks(html: string): any[] {
        // 使用非 dotAll 模式相容 ES6 target
        const match = html.match(/ytInitialPlayerResponse\s*=\s*\{/);
        if (match) {
            // 從匹配位置提取 JSON（找到第一個完整的 {...}）
            const start = html.indexOf('ytInitialPlayerResponse') + 'ytInitialPlayerResponse'.length;
            const eq    = html.indexOf('{', start);
            if (eq !== -1) {
                try {
                    // 用簡單的方法找到對應的閉括號
                    let depth = 0;
                    let end   = eq;
                    for (let i = eq; i < Math.min(eq + 500000, html.length); i++) {
                        if (html[i] === '{') depth++;
                        else if (html[i] === '}') { depth--; if (depth === 0) { end = i; break; } }
                    }
                    const playerResponse = JSON.parse(html.slice(eq, end + 1));
                    const tracks = playerResponse
                        ?.captions
                        ?.playerCaptionsTracklistRenderer
                        ?.captionTracks;
                    if (Array.isArray(tracks)) return tracks;
                } catch { /* 繼續備用方法 */ }
            }
        }
        // 備用：直接搜尋 captionTracks 片段
        const captionIdx = html.indexOf('"captionTracks":');
        if (captionIdx !== -1) {
            const arrStart = html.indexOf('[', captionIdx);
            if (arrStart !== -1) {
                // 找對應的 ]
                let depth = 0;
                let arrEnd = arrStart;
                for (let i = arrStart; i < Math.min(arrStart + 100000, html.length); i++) {
                    if (html[i] === '[') depth++;
                    else if (html[i] === ']') { depth--; if (depth === 0) { arrEnd = i; break; } }
                }
                try { return JSON.parse(html.slice(arrStart, arrEnd + 1)); } catch { /* 放棄 */ }
            }
        }
        return [];
    }

    private static selectTrack(tracks: any[], preferredLang: string): any {
        return (
            tracks.find(t => t.languageCode === preferredLang) ??
            tracks.find(t => t.languageCode.startsWith(preferredLang)) ??
            tracks.find(t => t.languageCode.startsWith('en')) ??
            tracks[0]
        );
    }

    private static buildSrv1Url(baseUrl: string): string {
        const url = new URL(baseUrl);
        url.searchParams.set('fmt', 'srv1');
        return url.toString();
    }

    private static buildJson3Url(baseUrl: string): string {
        const url = new URL(baseUrl);
        url.searchParams.set('fmt', 'json3');
        return url.toString();
    }
}
